


checking out Leons spatial data

```{r}

library(dplyr)
library(tidyr)
library(ComplexHeatmap)
```




```{r}

coronal_stats = data.table::fread('/vault/lfrench/mouse_brain_consensus_taxonomy_spatial/results/distance_stats.coronal.csv')

coronal_stats

```



```{r}

coronal_pairwise_stats = data.table::fread('/vault/lfrench/mouse_brain_consensus_taxonomy_spatial/results/pairwise_distances.coronal.csv')


vip_pairwise_coronal_dist = coronal_pairwise_stats %>% filter(grepl('Vip', supertype1) & grepl('Vip', supertype2) ) %>%
  select(supertype1, supertype2, wasserstein_distance) %>%
  pivot_wider(names_from = supertype2, values_from = wasserstein_distance)
vip_pairwise_coronal_dist = as.data.frame(vip_pairwise_coronal_dist)
rownames(vip_pairwise_coronal_dist) = vip_pairwise_coronal_dist$supertype1
vip_pairwise_coronal_dist = vip_pairwise_coronal_dist %>% select(-c(supertype1))
vip_pairwise_coronal_dist = as.matrix(vip_pairwise_coronal_dist)

col_fun = circlize::colorRamp2(breaks = c(0, max(vip_pairwise_coronal_dist, na.rm = T)), c('grey','red'))
Heatmap(vip_pairwise_coronal_dist, col = col_fun, clustering_method_columns = 'ward.D2',
        clustering_method_rows = 'ward.D2')


```















