---
title: "The misplaced mouse Pax6 interneuron subclass: A cross-species transcriptomic reassignment"
author: "Jonathan Werner"
date: "2026-08-11"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This markdown file contains the code for generating all plots for the publication:
Werner, Suresh, French, and Gillis. The misplaced mouse Pax6 interneuron subclass: A cross-species transcriptomic reassignment. 2026.

All data for these plots is provided at: https://github.com/JonathanMWerner/mammalian_brain_consensus_taxonomy/source_data/data_for_plots




```{r library_and_colors}
library(ggplot2)
library(dplyr)
library(MetaMarkers)
celltype_color_palette = c("Chandelier"='#F641A8', 
                           "Pvalb"='#D93137', 
                           "Sst"='#FF9900', 
                           "Sst Chodl"='#FFD700', 
                           "Lamp5"='#DA808C',
                           "Sncg"='#DF70FF',
                           "Vip"='#A45FBF', 
                           "Lamp5 Lhx6"='#935F50',
                           "Pax6"='#71238C',
                           'NA' = 'grey90')

```

## Figure 2 H


```{r mouse_pareto}
load(file = 'data_for_plots/mouse_meta_markers.Rdata')

plot_pareto_summary(mouse_subclass_meta_markers %>% filter(cell_type %in% c('Pax6','Sncg')), min_recurrence=4) +
  theme_bw() + scale_color_manual(values = celltype_color_palette) + ggtitle('Homologous Mouse subclass markers') + ylim(.5, 1) + xlim(0,5)

```


